In [153]:
from pathlib import Path
import pandas as pd
import re

In [154]:
base_path = Path("../data/bronze/laps/season=2026")

In [155]:
files = sorted(base_path.rglob("*.parquet"))
print(f"Found {len(files)} files")
for f in files:
    print(f"- {f}")

Found 3 files
- ..\data\bronze\laps\season=2026\round=01\laps.parquet
- ..\data\bronze\laps\season=2026\round=02\laps.parquet
- ..\data\bronze\laps\season=2026\round=03\laps.parquet

In [156]:
dfs = [pd.read_parquet(f) for f in files]
df = pd.concat(dfs, ignore_index=True)

In [157]:
df_silver = df.drop(columns=["FastF1Generated", "ingested_at_utc", "IsAccurate"])

In [158]:
key_cols = ["season", "round_number", "Driver", "LapNumber"]
dup_cnt = df_silver.duplicated(subset=key_cols).sum()
print(f"Duplicated by key: {dup_cnt}")

Duplicated by key: 0

In [159]:
df.to_csv("./cek_isi.csv", index=False)

**FUNCTION**

In [160]:
def check_null(column):
    amount = column.isna().sum()
    print(f"Null data for {column.name}: {amount}")
    if amount > 0:
        mask = column.isna()
        if mask.any():
            print(f"Rows with null in {column.name}:")
            display(df.loc[mask])
def strip_string(column):
    print(f"Stripping string for {column.name}")
    column = column.str.strip()
    
    return column

def upper_string(column):
    print(f"Uppercasing string for {column.name}")
    column = column.str.upper()

    return column

def clean_driver(column):
    column = strip_string(column)
    column = upper_string(column)

    return column

def convert_to_int(column):
    print(f"Converting to int for {column.name}")
    column = pd.to_numeric(column, errors="coerce")
    
    return column

**TIME**

In [161]:
check_null(df_silver["Time"])

Null data for Time: 0

**DRIVER**

In [162]:
check_null(df_silver["Driver"])
df_silver.value_counts("Driver")
df_silver["Driver"] = clean_driver(df_silver["Driver"])

Null data for Driver: 0
Stripping string for Driver
Uppercasing string for Driver

**DRIVER NUMBER**

In [163]:
check_null(df_silver["DriverNumber"])
df_silver["DriverNumber"] = convert_to_int(df_silver["DriverNumber"])

Null data for DriverNumber: 0
Converting to int for DriverNumber

**LAP TIME**

In [164]:
check_null(df_silver["LapTime"])
df_silver["is_LapTime_not_na"] = df_silver["LapTime"].notna()

Null data for LapTime: 48
Rows with null in LapTime:

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,season,round_number,event_name,session_type,ingested_at_utc
240,0 days 01:38:59.952000,ALO,14,NaT,13.0,2.0,NaT,0 days 01:22:49.657000,0 days 00:00:35.885000,0 days 00:00:25.378000,...,19.0,None,,False,False,2026,1,Australian Grand Prix,R,2026-04-27T11:14:12.581298+00:00
249,0 days 01:52:27.116000,ALO,14,NaT,22.0,3.0,NaT,0 days 01:52:27.205000,0 days 00:00:30.824000,0 days 00:00:30.521000,...,18.0,None,,False,False,2026,1,Australian Grand Prix,R,2026-04-27T11:14:12.581298+00:00
341,0 days 02:13:18.247000,STR,18,NaT,34.0,3.0,NaT,0 days 01:55:18.611000,0 days 00:00:30.496000,0 days 00:00:19.613000,...,17.0,None,,False,False,2026,1,Australian Grand Prix,R,2026-04-27T11:14:12.581298+00:00
408,0 days 01:03:51.908000,HUL,27,NaT,1.0,1.0,NaT,NaT,NaT,NaT,...,NaN,None,,True,False,2026,1,Australian Grand Prix,R,2026-04-27T11:14:12.581298+00:00
875,0 days 01:19:15.504000,HAD,6,NaT,11.0,1.0,NaT,NaT,NaT,NaT,...,NaN,None,None,True,False,2026,1,Australian Grand Prix,R,2026-04-27T11:14:12.581298+00:00
945,0 days 01:22:05.068000,BOT,77,NaT,12.0,1.0,NaT,0 days 01:21:36.868000,0 days 00:00:46.720000,0 days 00:00:45.988000,...,19.0,None,,False,False,2026,1,Australian Grand Prix,R,2026-04-27T11:14:12.581298+00:00
949,0 days 01:29:21.898000,BOT,77,NaT,16.0,2.0,NaT,NaT,NaT,NaT,...,NaN,None,None,True,False,2026,1,Australian Grand Prix,R,2026-04-27T11:14:12.581298+00:00
1007,0 days 00:58:03.760000,NOR,1,NaT,1.0,1.0,NaT,NaT,NaT,NaT,...,NaN,None,,True,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1018,0 days 01:15:47.651000,GAS,10,NaT,11.0,2.0,0 days 01:13:30.471000,NaT,0 days 00:00:54.680000,0 days 00:00:40.781000,...,9.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1019,0 days 01:18:17.634000,GAS,10,NaT,12.0,2.0,NaT,NaT,0 days 00:00:42.739000,0 days 00:00:44.215000,...,9.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1129,0 days 01:15:38.818000,ANT,12,NaT,11.0,2.0,0 days 01:13:12.979000,NaT,0 days 00:00:57.422000,0 days 00:00:45.272000,...,1.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1131,0 days 01:20:39.246000,ANT,12,NaT,13.0,2.0,NaT,NaT,0 days 00:00:37.267000,0 days 00:00:44.242000,...,1.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1217,0 days 01:15:45.025000,LEC,16,NaT,11.0,2.0,0 days 01:13:27.065000,NaT,0 days 00:00:57.124000,0 days 00:00:41.154000,...,7.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1218,0 days 01:18:15.130000,LEC,16,NaT,12.0,2.0,NaT,NaT,0 days 00:00:42.910000,0 days 00:00:44.533000,...,7.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1272,0 days 01:14:14.241000,STR,18,NaT,10.0,1.0,NaT,NaT,NaT,NaT,...,NaN,None,None,True,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1273,0 days 00:58:03.760000,ALB,23,NaT,1.0,1.0,NaT,NaT,NaT,NaT,...,NaN,None,,True,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1285,0 days 01:18:16.434000,HUL,27,NaT,12.0,1.0,NaT,NaT,0 days 00:00:42.774000,0 days 00:00:44.575000,...,8.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1373,0 days 02:13:50.686000,VER,3,NaT,45.0,2.0,NaT,0 days 02:13:48.930000,0 days 00:00:25.784000,0 days 00:00:54.024000,...,13.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1552,0 days 01:20:39.995000,COL,43,NaT,13.0,1.0,NaT,NaT,0 days 00:00:37.203000,0 days 00:00:44.278000,...,2.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1605,0 days 01:15:42.546000,HAM,44,NaT,11.0,2.0,0 days 01:13:20.846000,NaT,0 days 00:00:56.333000,0 days 00:00:42.193000,...,5.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1606,0 days 01:18:12.515000,HAM,44,NaT,12.0,2.0,NaT,NaT,0 days 00:00:43.585000,0 days 00:00:43.402000,...,5.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1651,0 days 00:58:03.760000,BOR,5,NaT,1.0,1.0,NaT,NaT,NaT,NaT,...,NaN,None,,True,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1717,0 days 01:16:41.638000,HAD,6,NaT,11.0,3.0,0 days 01:14:30.898000,NaT,0 days 00:00:56.842000,0 days 00:00:40.160000,...,17.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1773,0 days 01:15:41.722000,RUS,63,NaT,11.0,2.0,0 days 01:13:20.674000,NaT,0 days 00:00:55.148000,0 days 00:00:43.483000,...,4.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1829,0 days 01:16:24.050000,BOT,77,NaT,11.0,2.0,0 days 01:14:13.350000,NaT,0 days 00:00:58.486000,0 days 00:00:40.930000,...,16.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1874,0 days 00:58:03.760000,PIA,81,NaT,1.0,1.0,NaT,NaT,NaT,NaT,...,NaN,None,,True,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1885,0 days 01:15:58.226000,BEA,87,NaT,11.0,2.0,0 days 01:13:47.503000,NaT,0 days 00:00:52.490000,0 days 00:00:40.239000,...,10.0,None,,False,False,2026,2,Chinese Grand Prix,R,2026-04-27T11:13:56.741863+00:00
1955,0 days 01:46:45.624000,NOR,1,NaT,25.0,2.0,NaT,NaT,0 days 00:00:50.322000,0 days 00:01:12.179000,...,6.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2008,0 days 01:46:46.968000,GAS,10,NaT,25.0,2.0,NaT,NaT,0 days 00:00:50.269000,0 days 00:01:12.706000,...,7.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2112,0 days 01:41:37.205000,ANT,12,NaT,23.0,2.0,0 days 01:39:19.138000,NaT,0 days 00:01:03.960000,0 days 00:01:06.163000,...,1.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2113,0 days 01:44:07.409000,ANT,12,NaT,24.0,2.0,NaT,NaT,0 days 00:00:52.194000,0 days 00:01:11.277000,...,1.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2114,0 days 01:46:38.050000,ANT,12,NaT,25.0,2.0,NaT,NaT,0 days 00:00:51.530000,0 days 00:01:12.146000,...,1.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2219,0 days 01:46:43.472000,LEC,16,NaT,25.0,2.0,NaT,NaT,0 days 00:00:52.556000,0 days 00:01:11.423000,...,5.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2353,0 days 01:46:52.610000,HUL,27,NaT,25.0,2.0,NaT,NaT,0 days 00:00:48.372000,0 days 00:01:14.454000,...,12.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2406,0 days 01:46:47.348000,VER,3,NaT,25.0,2.0,NaT,NaT,0 days 00:00:50.008000,0 days 00:01:13.460000,...,8.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2459,0 days 01:46:48.954000,LAW,30,NaT,25.0,2.0,NaT,NaT,0 days 00:00:49.682000,0 days 00:01:12.857000,...,9.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2512,0 days 01:46:51.233000,OCO,31,NaT,25.0,2.0,NaT,NaT,0 days 00:00:49.613000,0 days 00:01:13.530000,...,11.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2565,0 days 01:46:54.634000,LIN,41,NaT,25.0,2.0,NaT,NaT,0 days 00:00:48.754000,0 days 00:01:15.450000,...,14.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2618,0 days 01:46:56.603000,COL,43,NaT,25.0,2.0,NaT,NaT,0 days 00:00:47.963000,0 days 00:01:15.812000,...,16.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2669,0 days 01:41:43.629000,HAM,44,NaT,23.0,2.0,0 days 01:39:27.806000,NaT,0 days 00:01:04.944000,0 days 00:01:02.009000,...,4.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2671,0 days 01:46:42.536000,HAM,44,NaT,25.0,2.0,NaT,NaT,0 days 00:00:52.871000,0 days 00:01:10.692000,...,4.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2724,0 days 01:46:50.195000,BOR,5,NaT,25.0,2.0,NaT,NaT,0 days 00:00:49.930000,0 days 00:01:12.806000,...,10.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2777,0 days 01:46:55.914000,SAI,55,NaT,25.0,2.0,NaT,NaT,0 days 00:00:48.023000,0 days 00:01:15.761000,...,15.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2830,0 days 01:46:53.872000,HAD,6,NaT,25.0,2.0,NaT,NaT,0 days 00:00:48.526000,0 days 00:01:14.831000,...,13.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2883,0 days 01:46:41.150000,RUS,63,NaT,25.0,2.0,NaT,NaT,0 days 00:00:51.128000,0 days 00:01:12.548000,...,3.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2935,0 days 01:46:39.043000,BOT,77,NaT,24.0,2.0,NaT,NaT,0 days 00:00:51.808000,0 days 00:01:11.819000,...,21.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
2988,0 days 01:46:39.734000,PIA,81,NaT,25.0,2.0,NaT,NaT,0 days 00:00:51.457000,0 days 00:01:11.673000,...,2.0,None,,False,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00
3037,0 days 01:38:59.334000,BEA,87,NaT,21.0,2.0,NaT,NaT,NaT,NaT,...,NaN,None,None,True,False,2026,3,Japanese Grand Prix,R,2026-04-27T11:13:40.663407+00:00

In [165]:
df_silver.info()
df_silver

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3038 entries, 0 to 3037
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                3038 non-null   timedelta64[ns]
 1   Driver              3038 non-null   object
 2   DriverNumber        3038 non-null   int64
 3   LapTime             2990 non-null   timedelta64[ns]
 4   LapNumber           3038 non-null   float64
 5   Stint               3038 non-null   float64
 6   PitOutTime          80 non-null     timedelta64[ns]
 7   PitInTime           84 non-null     timedelta64[ns]
 8   Sector1Time         2968 non-null   timedelta64[ns]
 9   Sector2Time         3029 non-null   timedelta64[ns]
 10  Sector3Time         3026 non-null   timedelta64[ns]
 11  Sector1SessionTime  2957 non-null   timedelta64[ns]
 12  Sector2SessionTime  3029 non-null   timedelta64[ns]
 13  Sector3SessionTime  3026 non-null   timedelta64[ns]
 14  SpeedI1             2627 non-null   float64
 15  SpeedI2             3029 non-null   float64
 16  SpeedFL             2945 non-null   float64
 17  SpeedST             2964 non-null   float64
 18  IsPersonalBest      3034 non-null   object
 19  Compound            3038 non-null   object
 20  TyreLife            3038 non-null   float64
 21  FreshTyre           3038 non-null   bool
 22  Team                3038 non-null   object
 23  LapStartTime        3038 non-null   timedelta64[ns]
 24  LapStartDate        0 non-null      datetime64[ns]
 25  TrackStatus         3038 non-null   object
 26  Position            3029 non-null   float64
 27  Deleted             0 non-null      object
 28  DeletedReason       3034 non-null   object
 29  season              3038 non-null   int64
 30  round_number        3038 non-null   int64
 31  event_name          3038 non-null   object
 32  session_type        3038 non-null   object
 33  is_LapTime_not_na   3038 non-null   bool
dtypes: bool(2), datetime64[ns](1), float64(8), int64(3), object(9), timedelta64[ns](11)
memory usage: 765.6+ KB

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,season,round_number,event_name,session_type,is_LapTime_not_na
0,0 days 01:03:56.437000,NOR,1,0 days 00:01:36.458000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:18.163000,...,NaT,1,6.0,None,,2026,1,Australian Grand Prix,R,True
1,0 days 01:05:23.781000,NOR,1,0 days 00:01:27.344000,2.0,1.0,NaT,NaT,0 days 00:00:31.074000,0 days 00:00:18.116000,...,NaT,1,6.0,None,,2026,1,Australian Grand Prix,R,True
2,0 days 01:06:50.644000,NOR,1,0 days 00:01:26.863000,3.0,1.0,NaT,NaT,0 days 00:00:30.541000,0 days 00:00:18.252000,...,NaT,1,7.0,None,,2026,1,Australian Grand Prix,R,True
3,0 days 01:08:16.501000,NOR,1,0 days 00:01:25.857000,4.0,1.0,NaT,NaT,0 days 00:00:30.190000,0 days 00:00:18.193000,...,NaT,1,7.0,None,,2026,1,Australian Grand Prix,R,True
4,0 days 01:09:42.074000,NOR,1,0 days 00:01:25.573000,5.0,1.0,NaT,NaT,0 days 00:00:29.930000,0 days 00:00:17.868000,...,NaT,1,7.0,None,,2026,1,Australian Grand Prix,R,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,0 days 01:31:41.771000,BEA,87,0 days 00:01:57.448000,17.0,2.0,0 days 01:30:08.107000,NaT,0 days 00:00:57.139000,0 days 00:00:41.840000,...,NaT,1,19.0,None,,2026,3,Japanese Grand Prix,R,True
3034,0 days 01:33:17.825000,BEA,87,0 days 00:01:36.054000,18.0,2.0,NaT,NaT,0 days 00:00:35.006000,0 days 00:00:42.424000,...,NaT,1,19.0,None,,2026,3,Japanese Grand Prix,R,True
3035,0 days 01:34:53.730000,BEA,87,0 days 00:01:35.905000,19.0,2.0,NaT,NaT,0 days 00:00:35.345000,0 days 00:00:42.252000,...,NaT,1,18.0,None,,2026,3,Japanese Grand Prix,R,True
3036,0 days 01:36:29.334000,BEA,87,0 days 00:01:35.604000,20.0,2.0,NaT,NaT,0 days 00:00:35.253000,0 days 00:00:42.310000,...,NaT,1,18.0,None,,2026,3,Japanese Grand Prix,R,True
3037,0 days 01:38:59.334000,BEA,87,NaT,21.0,2.0,NaT,NaT,NaT,NaT,...,NaT,124,NaN,None,None,2026,3,Japanese Grand Prix,R,False